id: ADC8A9A96
base_file: f8F69.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:06:41.974920
  last_modified_at: 2022-06-17 13:06:41.974925
