id: ADC8A9A96
base_file: f899A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:06:41.971342
  last_modified_at: 2022-06-17 13:06:41.971349
